### ISSUE TITLE
Exit Colors

### ISSUE THREAD

**Issue by ccubed** [ccubed/RFK#22]
exit colors to private builds to be a different color. If someone wants to do this, i will give you the builder bit.

**Comment by AJ-RfK** [comment]
http://musoapbox.net/topic/413/colorful-exits/ appears to have the answer, but I think it may need to be an actual staff thing. If someone wants to set up the exit parent so all I have to do is just enter the command over and over, I volunteer to roam the grid and set up private residences.

**Comment by ccubed** [comment]
The master room parent is #44. The builderbit should be able to change it. Tell me if you can't.

**Comment by AJ-RfK** [comment]
Okra, I can't change it with the builderbit. Let me know when it is!

**Comment by ccubed** [comment]
Okay, you should be able to change it now.

**Comment by ccubed** [comment]
Okay, so we'll do a test room. Set the attribute and tell me which one you set and I'll go test it. What color did you want?

**Comment by AJ-RfK** [comment]
Sorry; I was operating on not a lot of sleep earlier. I have set Arkham Motel (#527) at the Airport &private here=Y, as Xeth. I assume dark-yellow would be the least jarring, since the default is gray? (Or maybe white, but that seems more annoying.)

**Comment by ccubed** [comment]
Okay, I will test this out tonight.

**Comment by Zironic** [comment]
Well, the default colour is actually decided by their MU\* client, I believe most clients use some sort of gray on black background but I don't think you can count on that.

I think that like I wrote in the thread, if we're going to colour the exits why don't we colour more things then just Private?

For instance we could use firebrick2 for safe places, springgreen for Racks and other player controlled open spaces and Elysium could be goldenrod.

**Comment by AJ-RfK** [comment]
I was thinking dark yellow also because it's legible on both black and white backgrounds. I like that idea, Groth, but with tablet mushing, how can you guarantee all those colors? Maybe symbols (tildes, asterisks) are the way to go instead?

**Comment by ccubed** [comment]
I don't want to use 256 color for exits because not everyone has a client that supports it

**Comment by Zironic** [comment]
Good point, if you want to see all the colours and how they degrade on a client that only supports 16 colors, you can use this command:
think iter(colors(),ansi(+%i0,%i0 [ansi(colors(%i0,16color),colors(%i0,16color))]%r))

Some of them degrade in insane ways. I suggest 
palegreen2 which degrades into g for open places like Racks.
Wheat which degrades into wh for Elysium.
darkorange1 which degrades into r for closed places like Safe Place.

For colour blindness, we could use |Alias| for open places and \* Alias \* for closed places?

**Comment by AJ-RfK** [comment]
That seems sensible to me, Groth. Okra or you, give me a heads-up whenever you've got stuff coded and I'll gladly tag rooms.

**Comment by AJ-RfK** [comment]
Per Jakob, holding on this because he wants to adjust some stuff re. room parents.

**Comment by ccubed** [comment]
Okay, let me know when we are starting this again.
