### ISSUE TITLE
Beatcalc

### ISSUE THREAD

**Issue by ccubed** [ccubed/RFK#42]
Beatcalc appears to be calculating exp wrong. Bay's experience is showing off per the calculations though his calculations per the beats reported in +xp are right.

**Comment by Zironic** [comment]
As discussed in chat but I'll repeat here for clarity. The function correctly calculates spent and earned XP however it's impossible to accurately display Available XP if the spent XP does not add up to whole XP. The code was changed to round spent XP up to nearest whole XP which means that some characters will have -1 available XP.
