### ISSUE TITLE
Harpy/Prince Commands

### ISSUE THREAD

**Issue by Zironic** [ccubed/RFK#50]
We need to write a command so that the Harpy and Prince can change laurels by themselves. In order to achieve this I'm going to write two functions, one of which will need a new DB table.

+changelaurels Player=Amount
This function will simply change a characters status by <amount> and automatically do the relevant conversions.

+laurels Player=Amount/Reason/Cost
This will be a Trust but Verify function for the Prince and Harpies that will draw <cost> from their Laurel pool and change the players laurels by <amount>. This will also require the Prince and Harpies to receive a Laurel attribute that we'll have to update each cycle.

This function will require a new DB table that contains

```
<ID><Harpy>|<Character>|<Reason>|<Amount>|<Cost>|<Remaining Harpy Laurels>
```

I'm going to write the first function right now but I'll need Oukranos to create the new database table before I can write the second one.

**Comment by Zironic** [comment]
I've now written +stat/laurels Player=Amount/[Harpy]/[Cost] and +laurels Player=Amount/Reason:[cost].

Right now they're using xpaudit rather then their own table. 

Also by Baptistes request the +laurels command should automatically post to a bboard but I'm not sure how to write that.

We also need to set the laurels attribute to Wizard globally so people can't self-alter their laurel budget.

**Comment by ccubed** [comment]
This was set up
